import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Editprofilepage(),
        ]),
      ),
    );
  }
}

class Editprofilepage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 440,
          height: 952,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF343434),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(32),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 8,
                child: Container(
                  width: 429,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(width: 429, height: 44),
                      ),
                      Positioned(
                        left: 384.38,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 25.17,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 386.67,
                        top: 19.33,
                        child: Container(
                          width: 20.59,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: Colors.white),
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 19,
                        child: Text(
                          '9:43',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 175,
                top: 166,
                child: Container(
                  width: 78,
                  height: 76,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 78,
                          height: 76,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/78x76"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 141,
                top: 257,
                child: Text(
                  'Omar Radwan',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 22,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 356,
                child: Container(
                  width: 390,
                  height: 54,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF979797),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 18.19,
                        top: 18,
                        child: SizedBox(
                          width: 361.57,
                          height: 18,
                          child: Text(
                            'Omar',
                            style: TextStyle(
                              color: const Color(0xFF555555),
                              fontSize: 13,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 54,
                        child: Container(
                          width: 390,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE8E8E8),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 182,
                top: 82,
                child: Text(
                  'profile',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w700,
                    height: 0.97,
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 440,
                child: Container(
                  width: 390,
                  height: 54,
                  decoration: ShapeDecoration(
                    color: Colors.white.withValues(alpha: 168),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 18.19,
                        top: 18,
                        child: SizedBox(
                          width: 361.57,
                          height: 18,
                          child: Text(
                            'Radwan',
                            style: TextStyle(
                              color: const Color(0xFF555555),
                              fontSize: 13,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 54,
                        child: Container(
                          width: 390,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE8E8E8),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 524,
                child: Container(
                  width: 390,
                  height: 54,
                  decoration: ShapeDecoration(
                    color: const Color(0x00606060),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 81.87,
                        top: 18,
                        child: SizedBox(
                          width: 251.28,
                          height: 18,
                          child: Text(
                            'Phone number',
                            style: TextStyle(
                              color: const Color(0xFF555555),
                              fontSize: 13,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 54,
                        child: Container(
                          width: 390,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE8E8E8),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 32.97,
                        top: 17,
                        child: SizedBox(
                          width: 27.29,
                          child: Text(
                            '+49',
                            style: TextStyle(
                              color: const Color(0xFF555555),
                              fontSize: 13,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 88,
                top: 794,
                child: Container(
                  width: 259.82,
                  height: 55,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 259.82,
                          height: 55,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF14AE5C),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(15),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 76,
                        top: 19,
                        child: SizedBox(
                          width: 107,
                          child: Opacity(
                            opacity: 0.91,
                            child: Text(
                              'Update Profile',
                              textAlign: TextAlign.center,
                              style: TextStyle(
                                color: Colors.white,
                                fontSize: 15,
                                fontFamily: 'DM Sans',
                                fontWeight: FontWeight.w500,
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 608,
                child: Container(
                  width: 390,
                  height: 54,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF767676),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(10),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 18.19,
                        top: 18,
                        child: SizedBox(
                          width: 313.82,
                          height: 18,
                          child: Text(
                            'Select your gender',
                            style: TextStyle(
                              color: const Color(0xFF555555),
                              fontSize: 13,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 54,
                        child: Container(
                          width: 390,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE8E8E8),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 83,
                top: 297,
                child: Text(
                  'omarahmedmohamedtaha.radwan@ue-germany.de',
                  style: TextStyle(
                    color: const Color(0xFFB4B4BE),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 692,
                child: Container(
                  width: 390,
                  height: 54,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 18.19,
                        top: 18,
                        child: SizedBox(
                          width: 313.82,
                          height: 18,
                          child: Text(
                            'What is your date of birth?',
                            style: TextStyle(
                              color: const Color(0xFF555555),
                              fontSize: 13,
                              fontFamily: 'DM Sans',
                              fontWeight: FontWeight.w400,
                              height: 1.50,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 54,
                        child: Container(
                          width: 390,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: const Color(0xFFE8E8E8),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 350,
                        top: 13,
                        child: Container(width: 28, height: 23, child: Stack()),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 62,
                child: Container(
                  width: 22,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 27,
                top: 926,
                child: Container(
                  width: 375,
                  height: 34,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 121,
                        top: 21,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: const Color(0x7FB9C1D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}