import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Profilepage(),
        ]),
      ),
    );
  }
}

class Profilepage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 445,
          height: 952,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF343434),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(32),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 21,
                top: 89,
                child: Container(
                  width: 47,
                  height: 49,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 47,
                          height: 49,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/47x49"),
                              fit: BoxFit.cover,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 26,
                top: 25,
                child: Text(
                  '9:42',
                  style: TextStyle(
                    color: const Color(0xFFF5F5F5),
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 21.30,
                top: 148,
                child: SizedBox(
                  width: 118.60,
                  height: 20.47,
                  child: Text(
                    'Your total balance',
                    style: TextStyle(
                      color: const Color(0xFFF6F6F6),
                      fontSize: 14,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.43,
                      letterSpacing: 0.25,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 170.30,
                child: Text(
                  '\$87,430.12',
                  style: TextStyle(
                    color: const Color(0xFFFEFEFE),
                    fontSize: 24,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w700,
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 208.30,
                child: Text(
                  '\$1,521.4',
                  style: TextStyle(
                    color: const Color(0xFFFEFEFE),
                    fontSize: 12,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.67,
                    letterSpacing: 0.10,
                  ),
                ),
              ),
              Positioned(
                left: -9,
                top: 864,
                child: Container(
                  width: 454,
                  height: 95,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 9.05,
                        child: Container(
                          width: 454,
                          height: 85.95,
                          decoration: BoxDecoration(
                            color: const Color(0xFF434343),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x19000000),
                                blurRadius: 1,
                                offset: Offset(0, -1),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 195.57,
                        top: 2.26,
                        child: Container(
                          width: 65.19,
                          height: 63.33,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF606060),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(50),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 8,
                                offset: Offset(0, 2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 214.19,
                        top: 20.36,
                        child: Container(
                          width: 27.94,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 303.83,
                        top: 21.49,
                        child: Container(
                          width: 27.94,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 38.42,
                        top: 21.49,
                        child: Container(
                          width: 27.94,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 34.59,
                        top: 52.02,
                        child: Text(
                          'Home',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 114.25,
                        top: 52.02,
                        child: Text(
                          'Business \nNews',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 297.52,
                        top: 52.02,
                        child: Text(
                          'View\nMarket',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 387.15,
                        top: 52.02,
                        child: Text(
                          'Profile',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF007AFF) /* Miscellaneous-Floating-Tab---Text-Selected */,
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 126.89,
                        top: 21.49,
                        child: Container(
                          width: 27.94,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 392.30,
                        top: 21.49,
                        child: Container(
                          width: 27.94,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 352.96,
                top: 295.45,
                child: Opacity(
                  opacity: 0.30,
                  child: Container(
                    width: 62,
                    height: 62,
                    decoration: ShapeDecoration(
                      gradient: RadialGradient(
                        center: Alignment(0.50, 0.50),
                        radius: 0.66,
                        colors: [const Color(0xFFDF1525), const Color(0x00DF1525)],
                      ),
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 376.07,
                top: 319.50,
                child: Container(
                  width: 16,
                  height: 16,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFF9B9B),
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 3,
                        color: const Color(0xFF202020),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 299,
                top: 269.50,
                child: Container(
                  width: 85,
                  height: 45,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFF9B9B),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.only(
                        topLeft: Radius.circular(8),
                        topRight: Radius.circular(8),
                        bottomLeft: Radius.circular(8),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 383,
                top: 307.50,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 15,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFFFF9B9B),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 316.26,
                top: 294.07,
                child: SizedBox(
                  width: 64.87,
                  height: 20.43,
                  child: Text(
                    '15.780,01',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.43,
                      letterSpacing: 0.25,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 316.26,
                top: 277.72,
                child: SizedBox(
                  width: 36.49,
                  height: 20.43,
                  child: Text(
                    'NYSE',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.43,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 184.57,
                top: 342.20,
                child: SizedBox(
                  width: 15.88,
                  child: Text(
                    '1H',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Eudoxus Sans',
                      fontWeight: FontWeight.w700,
                      height: 1.33,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 223.15,
                top: 342.20,
                child: SizedBox(
                  width: 19.29,
                  child: Text(
                    '4H',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Eudoxus Sans',
                      fontWeight: FontWeight.w700,
                      height: 1.33,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 265.13,
                top: 342.20,
                child: SizedBox(
                  width: 15.88,
                  child: Text(
                    '1D',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Eudoxus Sans',
                      fontWeight: FontWeight.w700,
                      height: 1.33,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 303.70,
                top: 342.20,
                child: SizedBox(
                  width: 18.15,
                  child: Text(
                    '7D',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Eudoxus Sans',
                      fontWeight: FontWeight.w700,
                      height: 1.33,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 131.25,
                top: 342.20,
                child: SizedBox(
                  width: 30.63,
                  child: Text(
                    '30m',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Eudoxus Sans',
                      fontWeight: FontWeight.w700,
                      height: 1.33,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 179.01,
                top: 174,
                child: Opacity(
                  opacity: 0.80,
                  child: Container(
                    width: 62.85,
                    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                    clipBehavior: Clip.antiAlias,
                    decoration: ShapeDecoration(
                      color: const Color(0xFFEB221E) /* Background-Danger-Default */,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(10),
                      ),
                      shadows: [
                        BoxShadow(
                          color: Color(0x00F61C7A),
                          blurRadius: 24,
                          offset: Offset(0, 8),
                          spreadRadius: 0,
                        )
                      ],
                    ),
                    child: Row(
                      mainAxisSize: MainAxisSize.min,
                      mainAxisAlignment: MainAxisAlignment.start,
                      crossAxisAlignment: CrossAxisAlignment.center,
                      spacing: 4,
                      children: [
                        Text(
                          '810%',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 423,
                child: Container(
                  width: 200,
                  height: 237,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(32),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 200,
                          height: 209.07,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF01060D),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(32),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 113,
                        top: 74,
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF14AE5C) /* Background-Positive-Default */,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 4,
                            children: [
                              Text(
                                '0.59%',
                                style: TextStyle(
                                  color: Colors.black,
                                  fontSize: 12,
                                  fontFamily: 'Poppins',
                                  fontWeight: FontWeight.w600,
                                  height: 1.67,
                                  letterSpacing: 0.10,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 105,
                        child: SizedBox(
                          width: 43.64,
                          child: Text(
                            '\$367.67',
                            style: TextStyle(
                              color: const Color(0xFFBDBDBD),
                              fontSize: 11,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.82,
                              letterSpacing: 0.10,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 74,
                        child: SizedBox(
                          width: 56.36,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '\$365',
                                  style: TextStyle(
                                    color: Colors.white /* Miscellaneous-Floating-Tab---Pill-Fill */,
                                    fontSize: 14,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.71,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                                TextSpan(
                                  text: '.51',
                                  style: TextStyle(
                                    color: const Color(0xFFDADADA),
                                    fontSize: 14,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.71,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21.82,
                        top: 74.49,
                        child: Container(
                          width: 1.82,
                          height: 47.40,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFFF9B9B),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 80,
                        top: 35,
                        child: SizedBox(
                          width: 98.18,
                          child: Text(
                            'Facebook, Inc',
                            style: TextStyle(
                              color: Colors.white /* Miscellaneous-Floating-Tab---Pill-Fill */,
                              fontSize: 12,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.33,
                              letterSpacing: 0.40,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 80,
                        top: 6,
                        child: SizedBox(
                          width: 98.18,
                          child: Text(
                            'FB',
                            style: TextStyle(
                              color: Colors.white /* Miscellaneous-Floating-Tab---Pill-Fill */,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.50,
                              letterSpacing: 0.10,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21.82,
                        top: 20.31,
                        child: Container(
                          width: 43.64,
                          height: 40.63,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 227,
                top: 423,
                child: Container(
                  width: 200,
                  height: 237,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(32),
                    ),
                  ),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 200,
                          height: 209.07,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF01060D),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(32),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 101.41,
                        top: 76.34,
                        child: Container(
                          padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                          decoration: ShapeDecoration(
                            color: const Color(0xFFBF0F0C) /* Background-Danger-Hover */,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3DFF6740),
                                blurRadius: 24,
                                offset: Offset(0, 8),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 4,
                            children: [
                              Text(
                                '0.59%',
                                style: TextStyle(
                                  color: const Color(0xFF0C0C0D) /* Text-Utilities-Text-On-Overlay */,
                                  fontSize: 12,
                                  fontFamily: 'Eudoxus Sans',
                                  fontWeight: FontWeight.w700,
                                  height: 1.33,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29,
                        top: 105,
                        child: SizedBox(
                          width: 39.09,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '\$149',
                                  style: TextStyle(
                                    color: const Color(0xFFEBEDF0) /* Miscellaneous-Keyboard-Accessory-Bar---Selection */,
                                    fontSize: 11,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.82,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                                TextSpan(
                                  text: '.71',
                                  style: TextStyle(
                                    color: const Color(0xFFBDBDBD),
                                    fontSize: 11,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.82,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 29.49,
                        top: 71,
                        child: SizedBox(
                          width: 56.36,
                          child: Text.rich(
                            TextSpan(
                              children: [
                                TextSpan(
                                  text: '\$149',
                                  style: TextStyle(
                                    color: Colors.white /* Miscellaneous-Floating-Tab---Pill-Fill */,
                                    fontSize: 14,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.71,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                                TextSpan(
                                  text: '.62',
                                  style: TextStyle(
                                    color: const Color(0xFFDADADA),
                                    fontSize: 14,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.71,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                              ],
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21.82,
                        top: 74.49,
                        child: Container(
                          width: 1.82,
                          height: 47.40,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF6BBDFF),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(1)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 80,
                        top: 35,
                        child: SizedBox(
                          width: 98.18,
                          child: Text(
                            'Apple',
                            style: TextStyle(
                              color: Colors.white /* Miscellaneous-Floating-Tab---Pill-Fill */,
                              fontSize: 12,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.33,
                              letterSpacing: 0.40,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 80,
                        top: 6,
                        child: SizedBox(
                          width: 98.18,
                          child: Text(
                            'AAPL',
                            style: TextStyle(
                              color: Colors.white /* Miscellaneous-Floating-Tab---Pill-Fill */,
                              fontSize: 16,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.50,
                              letterSpacing: 0.10,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 21.82,
                        top: 20.31,
                        child: Container(
                          width: 43.64,
                          height: 40.63,
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 398.02,
                top: 651,
                child: Container(
                  width: 28.98,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 19,
                top: 651,
                child: SizedBox(
                  width: 173,
                  child: Text(
                    'Upgrade to premium',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.71,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 703,
                child: Container(
                  width: 411,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 57.68,
                          height: 48,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/58x48"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF606060),
                              ),
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 74.51,
                        top: 3,
                        child: Text(
                          'MSFT',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 360.91,
                        top: 3,
                        child: Text(
                          '\$213.10',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 366.36,
                        top: 26,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 1,
                          children: [
                            Container(
                              width: 12,
                              height: 12,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              '2.5%',
                              style: TextStyle(
                                color: const Color(0xFFBF0F0C) /* Icon-Danger-Secondary */,
                                fontSize: 12,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w400,
                                height: 1.33,
                                letterSpacing: 0.40,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Positioned(
                        left: 74.51,
                        top: 26,
                        child: Text(
                          'Microsoft Corp.',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 779,
                child: Container(
                  width: 410,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 57.54,
                          height: 48,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/58x48"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF606060),
                              ),
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 74.33,
                        top: 3,
                        child: Text(
                          'GOOGL',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 359.06,
                        top: 3,
                        child: Text(
                          '\$213.10',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 365.42,
                        top: 26,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 1,
                          children: [
                            Container(
                              width: 12,
                              height: 12,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              '1.1%',
                              style: TextStyle(
                                color: const Color(0xFF07F7B4),
                                fontSize: 12,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w400,
                                height: 1.33,
                                letterSpacing: 0.40,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Positioned(
                        left: 74.33,
                        top: 26,
                        child: Text(
                          'Alphabet Inc.',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 22,
                top: 55,
                child: Container(
                  width: 22,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 10,
                top: 382,
                child: Container(
                  width: 411,
                  height: 29,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1D82CC),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(32),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 35,
                top: 383,
                child: Text(
                  'Portfolio',
                  style: TextStyle(
                    color: const Color(0xFFFEFEFE),
                    fontSize: 16,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.50,
                    letterSpacing: 0.10,
                  ),
                ),
              ),
              Positioned(
                left: 350,
                top: 385,
                child: Text(
                  'View all',
                  textAlign: TextAlign.right,
                  style: TextStyle(
                    color: const Color(0xFF090909),
                    fontSize: 14,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w600,
                    height: 1.43,
                    letterSpacing: 0.10,
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 11,
                child: Container(
                  width: 375,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(width: 375, height: 44),
                      ),
                      Positioned(
                        left: 336,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 338,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: Colors.white),
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}