import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Applestock(),
        ]),
      ),
    );
  }
}

class Applestock extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 440,
          height: 952,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF343434),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(32),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 24,
                top: 57,
                child: Container(
                  width: 28.49,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 162.84,
                top: 60,
                child: SizedBox(
                  width: 160.26,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'APPL ',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 22,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.27,
                          ),
                        ),
                        TextSpan(
                          text: '(Apple)',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.75,
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              Positioned(
                left: 128,
                top: 59.50,
                child: Container(
                  width: 39,
                  height: 32.72,
                  decoration: ShapeDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/39x33"),
                      fit: BoxFit.cover,
                    ),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFFEEEEEE),
                      ),
                      borderRadius: BorderRadius.circular(24),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 395.51,
                top: 53,
                child: Container(
                  width: 28.49,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 18,
                top: 112,
                child: Container(
                  width: 406,
                  height: 40,
                  padding: const EdgeInsets.all(6),
                  clipBehavior: Clip.antiAlias,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF0F3D62),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Expanded(
                        child: Container(
                          height: double.infinity,
                          padding: const EdgeInsets.symmetric(horizontal: 8),
                          decoration: ShapeDecoration(
                            color: const Color(0xFF202020),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.only(
                                topLeft: Radius.circular(4),
                                bottomLeft: Radius.circular(4),
                              ),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Text(
                                'Summary',
                                style: TextStyle(
                                  color: const Color(0xFF89B8FF),
                                  fontSize: 14,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          height: double.infinity,
                          padding: const EdgeInsets.symmetric(horizontal: 8),
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(side: BorderSide(width: 1)),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Text(
                                'Analysis',
                                style: TextStyle(
                                  color: const Color(0xFFFEFEFE),
                                  fontSize: 14,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Expanded(
                        child: Container(
                          height: double.infinity,
                          padding: const EdgeInsets.symmetric(horizontal: 8),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            spacing: 10,
                            children: [
                              Text(
                                'Live Trade',
                                style: TextStyle(
                                  color: const Color(0xFFFEFEFE),
                                  fontSize: 14,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w500,
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 136.12,
                top: 231,
                child: SizedBox(
                  width: 199.64,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: '+2,02 (0,90%) ',
                          style: TextStyle(
                            color: const Color(0xFFFF9B9B),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                        TextSpan(
                          text: 'Today',
                          style: TextStyle(
                            color: const Color(0xFF6BBDFF),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              Positioned(
                left: 138.84,
                top: 248.75,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                  width: 32.59,
                  height: 24.57,
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 129.33,
                top: 180,
                child: SizedBox(
                  width: 183.35,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: '\$209',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 40,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 0.70,
                          ),
                        ),
                        TextSpan(
                          text: '.28',
                          style: TextStyle(
                            color: const Color(0xFFBDBDBD),
                            fontSize: 24,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.17,
                          ),
                        ),
                      ],
                    ),
                    textAlign: TextAlign.center,
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 617.53,
                child: Container(
                  width: 392.89,
                  height: 221.80,
                  decoration: ShapeDecoration(
                    color: Colors.black,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    shadows: [
                      BoxShadow(
                        color: Color(0x3F000000),
                        blurRadius: 4,
                        offset: Offset(0, 1),
                        spreadRadius: 0,
                      )
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 293.23,
                top: 717.74,
                child: SizedBox(
                  width: 106.84,
                  height: 19.70,
                  child: Text(
                    'Market Cap',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8198A5),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 293.23,
                top: 741.13,
                child: SizedBox(
                  width: 106.84,
                  height: 29.55,
                  child: Text(
                    '43.419B',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 172.60,
                top: 717.74,
                child: SizedBox(
                  width: 106.84,
                  height: 19.70,
                  child: Text(
                    'Avg. Volume',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8198A5),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 172.60,
                top: 741.13,
                child: SizedBox(
                  width: 106.84,
                  height: 29.55,
                  child: Text(
                    '1,461,009',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 51.98,
                top: 717.74,
                child: SizedBox(
                  width: 106.84,
                  height: 19.70,
                  child: Text(
                    'Volume',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8198A5),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 51.98,
                top: 741.13,
                child: SizedBox(
                  width: 106.84,
                  height: 29.55,
                  child: Text(
                    '834,146',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 293.23,
                top: 643.87,
                child: SizedBox(
                  width: 106.84,
                  height: 19.70,
                  child: Text(
                    'Low',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8198A5),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 293.23,
                top: 667.26,
                child: SizedBox(
                  width: 106.84,
                  height: 29.55,
                  child: Text(
                    '224.10',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF6BBDFF),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 172.60,
                top: 643.87,
                child: SizedBox(
                  width: 106.84,
                  height: 19.70,
                  child: Text(
                    'High',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8198A5),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 172.60,
                top: 667.26,
                child: SizedBox(
                  width: 106.84,
                  height: 29.55,
                  child: Text(
                    '227.29',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFE684FF),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 51.98,
                top: 643.87,
                child: SizedBox(
                  width: 106.84,
                  height: 19.70,
                  child: Text(
                    'Open',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF8198A5),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 51.98,
                top: 667.26,
                child: SizedBox(
                  width: 106.84,
                  height: 29.55,
                  child: Text(
                    '224.54',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFFB129),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: 570,
                child: SizedBox(
                  width: 375.66,
                  height: 29.55,
                  child: Text(
                    'Statistics',
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45.25,
                top: 511.83,
                child: Container(width: 74.51, height: 24.57),
              ),
              Positioned(
                left: 71.04,
                top: 514,
                child: SizedBox(
                  width: 24.07,
                  child: Text(
                    '12H',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.67,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 119.76,
                top: 511.83,
                child: Container(width: 74.51, height: 24.57),
              ),
              Positioned(
                left: 149.56,
                top: 514,
                child: SizedBox(
                  width: 16.05,
                  child: Text(
                    '1D',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.67,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 194.27,
                top: 511.83,
                child: Container(width: 74.51, height: 24.57),
              ),
              Positioned(
                left: 205.73,
                top: 511.83,
                child: Container(
                  width: 52.73,
                  height: 24.57,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFFF9B9B),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(12),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 221.78,
                top: 514,
                child: SizedBox(
                  width: 20.63,
                  child: Text(
                    '1W',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.67,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 268.78,
                top: 511.83,
                child: Container(width: 74.51, height: 24.57),
              ),
              Positioned(
                left: 297.44,
                top: 514,
                child: SizedBox(
                  width: 18.34,
                  child: Text(
                    '1M',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.67,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 343.29,
                top: 511.83,
                child: Container(width: 74.51, height: 24.57),
              ),
              Positioned(
                left: 373.67,
                top: 514,
                child: SizedBox(
                  width: 14.90,
                  child: Text(
                    '1Y',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 12,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.67,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 44,
                top: 276,
                child: Container(
                  width: 374,
                  height: 200,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 53.76,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'Mo',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 99.50,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'Tu',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 145.25,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'We',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 191,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'Th',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 236.75,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'Fr',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 282.50,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'Sa',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 328.25,
                        top: 184,
                        child: SizedBox(
                          width: 45.75,
                          child: Text(
                            'Su',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 44.61,
                          child: Text(
                            '\$280',
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 40,
                        child: SizedBox(
                          width: 44.61,
                          child: Text(
                            '\$260',
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 80,
                        child: SizedBox(
                          width: 44.61,
                          child: Text(
                            '\$240',
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 120,
                        child: SizedBox(
                          width: 44.61,
                          child: Text(
                            '\$220',
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 160,
                        child: SizedBox(
                          width: 44.61,
                          child: Text(
                            '\$200',
                            style: TextStyle(
                              color: const Color(0xFFEFEFEF),
                              fontSize: 14,
                              fontFamily: 'Roboto',
                              fontWeight: FontWeight.w400,
                              height: 1.43,
                              letterSpacing: 0.25,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 156.69,
                        top: 72,
                        child: Container(
                          width: 73.20,
                          height: 20,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFFEFEFE),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(10),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x668EE5CB),
                                blurRadius: 24,
                                offset: Offset(0, 8),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 168.03,
                        top: 74,
                        child: SizedBox(
                          width: 50.30,
                          child: Text(
                            '\$244.21',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.black,
                              fontSize: 12,
                              fontFamily: 'Poppins',
                              fontWeight: FontWeight.w600,
                              height: 1.67,
                              letterSpacing: 0.10,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 24,
                top: 858,
                child: Container(
                  width: 180,
                  height: 69,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF434343),
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 1,
                        color: const Color(0xFF767676),
                      ),
                      borderRadius: BorderRadius.circular(8),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Container(
                        width: 24,
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Stack(),
                      ),
                      Text(
                        'Add Liqudity',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: const Color(0xFFFBFBFB),
                          fontSize: 19,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 307,
                top: 858,
                child: Container(
                  width: 111,
                  height: 63,
                  padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 12.50),
                  decoration: ShapeDecoration(
                    color: const Color(0xFF14AE5C) /* Background-Positive-Default */,
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    spacing: 10,
                    children: [
                      Text(
                        'Trade',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.black,
                          fontSize: 20,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w500,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 11,
                top: 9,
                child: Container(
                  width: 429,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(width: 429, height: 44),
                      ),
                      Positioned(
                        left: 384.38,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 25.17,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 386.67,
                        top: 19.33,
                        child: Container(
                          width: 20.59,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: Colors.white),
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 19,
                        child: Text(
                          '9:43',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 16,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w900,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 39,
                top: 927,
                child: Container(
                  width: 375,
                  height: 34,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 121,
                        top: 21,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: const Color(0x7FB9C1D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}