import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../providers/news_provider.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [NewsPage()])),
    );
  }
}

class NewsPage extends StatelessWidget {
  final List<Map<String, dynamic>> curatedNews = [
    {
      'title': 'Fed Rate Decision: Market Impact Analysis for March 2024',
      'summary':
          'Federal Reserve expected to begin rate cuts in Q2 2024, potentially starting in June. Markets show increased volatility in anticipation.',
      'fullContent': '''
The Federal Reserve's upcoming decisions in 2024 are poised to significantly impact market dynamics. With inflation showing consistent signs of cooling, analysts are focusing on the timing of potential rate cuts.

Key Expectations:
• First rate cut likely in June 2024
• Total of 3-4 cuts expected throughout 2024
• Target rate projected to reach 4.5% by year-end

Market Implications:
- Tech stocks expected to benefit from lower rates
- Banking sector preparing for margin adjustments
- Real estate market anticipating increased activity

Expert Analysis:
"The Fed's transition from fighting inflation to supporting growth will be this year's key market driver," notes Sarah Chen, Chief Market Strategist at Global Markets Research. "Early indicators suggest a careful approach to rate reductions, with particular attention to employment data and core inflation metrics."

Investment Opportunities:
• Growth stocks likely to outperform
• Bond market repositioning expected
• Real estate sector showing early momentum
      ''',
      'date': 'March 15, 2024',
      'source': 'Market Strategy Weekly',
      'category': 'Monetary Policy',
    },
    {
      'title': 'AI Sector Outlook: Q2 2024 Growth Projections',
      'summary':
          'Major tech companies set to release new AI products in Q2, with significant implications for semiconductor and cloud computing stocks.',
      'fullContent': '''
The artificial intelligence sector is preparing for a transformative second quarter, with multiple major product launches and technological breakthroughs expected.

Upcoming Catalysts:
• New AI chip releases from leading manufacturers
• Enterprise AI platform expansions
• Major cloud providers upgrading AI infrastructure

Market Impact Predictions:
- Semiconductor stocks expected to see increased demand
- Cloud computing providers likely to benefit
- AI-focused startups attracting significant investment

Key Companies to Watch:
- NVIDIA: New AI chip architecture launch
- AMD: Enhanced AI processing capabilities
- Microsoft: Azure AI platform expansion
- Google: Advanced language model deployment

Industry Expert View:
"Q2 2024 represents a critical phase in AI commercialization," explains Dr. James Wong, AI Industry Analyst. "We're seeing a shift from research to practical applications, which could drive significant market opportunities."

Investment Considerations:
• Semiconductor sector momentum
• Cloud computing infrastructure plays
• AI software and services expansion
      ''',
      'date': 'March 18, 2024',
      'source': 'Tech Market Insights',
      'category': 'Technology',
    },
    {
      'title': 'Global Supply Chain Shift: Asian Markets in Focus',
      'summary':
          'Major manufacturing relocations and trade agreements expected to reshape Asian markets in Q2 2024, creating new investment opportunities.',
      'fullContent': '''
Asian markets are poised for significant transformation as global companies accelerate manufacturing diversification and new trade agreements take effect.

Emerging Trends:
• Manufacturing shift to Southeast Asia
• New regional trade partnerships
• Technology sector expansion in South Korea and Taiwan

Market Opportunities:
- Vietnamese manufacturing stocks
- Indian technology sector
- Singapore financial services
- Indonesian consumer markets

Economic Impact:
"The redistribution of manufacturing capacity across Asia creates unique investment opportunities," states Michelle Lee, Asian Markets Analyst at Eastern Capital. "Countries with strong infrastructure and favorable policies are likely to see increased foreign investment and economic growth."

Key Developments to Watch:
• New trade agreement implementations
• Infrastructure project announcements
• Foreign investment policy changes
• Technology sector expansions

Investment Sectors:
- Manufacturing and logistics
- Technology and semiconductors
- Financial services
- Consumer markets
      ''',
      'date': 'March 20, 2024',
      'source': 'Asian Markets Review',
      'category': 'Global Markets',
    },
    {
      'title': 'Energy Market Transformation: Q2 2024 Outlook',
      'summary':
          'Renewable energy sector expected to see major policy support and investment growth, while traditional energy adapts to changing market dynamics.',
      'fullContent': '''
The energy sector is approaching a critical transition period in Q2 2024, with both renewable and traditional energy markets facing significant changes.

Key Trends:
• Renewable energy policy initiatives
• Traditional energy adaptation strategies
• Energy storage technology advancement
• Grid infrastructure modernization

Market Projections:
- Solar sector growth acceleration
- Wind energy project expansions
- Battery technology investments
- Traditional energy transformation

Expert Insight:
"The energy sector is at an inflection point," notes Dr. Sarah Martinez, Energy Sector Analyst. "Policy support for renewables, combined with technological advances, is creating compelling investment opportunities while traditional energy companies are strategically repositioning."

Investment Opportunities:
• Solar technology companies
• Grid infrastructure providers
• Energy storage solutions
• Traditional energy transition plays

Regulatory Impact:
- New clean energy incentives
- Grid modernization funding
- Carbon pricing initiatives
- Energy efficiency standards
      ''',
      'date': 'March 21, 2024',
      'source': 'Energy Market Report',
      'category': 'Energy',
    },
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        title: const Text(
          'Market News',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
        centerTitle: true,
      ),
      body: Container(
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [
              Theme.of(context).primaryColor,
              Theme.of(context).colorScheme.background,
            ],
          ),
        ),
        child: SafeArea(
          child: ListView.builder(
            padding: const EdgeInsets.all(16),
            itemCount: curatedNews.length,
            itemBuilder: (context, index) {
              final article = curatedNews[index];
              return NewsCard(
                title: article['title']!,
                summary: article['summary']!,
                fullContent: article['fullContent']!,
                date: article['date']!,
                source: article['source']!,
                category: article['category']!,
              );
            },
          ),
        ),
      ),
    );
  }
}

class NewsCard extends StatefulWidget {
  final String title;
  final String summary;
  final String fullContent;
  final String date;
  final String source;
  final String category;

  const NewsCard({
    Key? key,
    required this.title,
    required this.summary,
    required this.fullContent,
    required this.date,
    required this.source,
    required this.category,
  }) : super(key: key);

  @override
  State<NewsCard> createState() => _NewsCardState();
}

class _NewsCardState extends State<NewsCard> {
  bool _isExpanded = false;

  @override
  Widget build(BuildContext context) {
    return Card(
      margin: const EdgeInsets.only(bottom: 16),
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)),
      color: Theme.of(context).primaryColor.withOpacity(0.3),
      child: InkWell(
        onTap: () {
          setState(() {
            _isExpanded = !_isExpanded;
          });
        },
        borderRadius: BorderRadius.circular(16),
        child: AnimatedContainer(
          duration: const Duration(milliseconds: 300),
          padding: const EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Row(
                children: [
                  Container(
                    padding: const EdgeInsets.symmetric(
                      horizontal: 8,
                      vertical: 4,
                    ),
                    decoration: BoxDecoration(
                      color: Colors.blue.withOpacity(0.2),
                      borderRadius: BorderRadius.circular(8),
                    ),
                    child: Text(
                      widget.category,
                      style: const TextStyle(
                        color: Colors.blue,
                        fontSize: 12,
                        fontWeight: FontWeight.bold,
                      ),
                    ),
                  ),
                  const Spacer(),
                  Text(
                    widget.date,
                    style: TextStyle(
                      color: Colors.white.withOpacity(0.6),
                      fontSize: 12,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 12),
              Text(
                widget.title,
                style: const TextStyle(
                  fontSize: 18,
                  fontWeight: FontWeight.bold,
                  color: Colors.white,
                ),
              ),
              const SizedBox(height: 8),
              Text(
                _isExpanded ? widget.fullContent : widget.summary,
                style: TextStyle(
                  fontSize: 14,
                  color: Colors.white.withOpacity(0.8),
                ),
              ),
              const SizedBox(height: 12),
              Row(
                children: [
                  Text(
                    widget.source,
                    style: TextStyle(
                      color: Colors.white.withOpacity(0.6),
                      fontSize: 12,
                      fontWeight: FontWeight.w500,
                    ),
                  ),
                  const Spacer(),
                  Icon(
                    _isExpanded ? Icons.expand_less : Icons.expand_more,
                    color: Colors.white.withOpacity(0.6),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }
}
