import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Businessnewspage(),
        ]),
      ),
    );
  }
}

class Businessnewspage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 439,
          height: 952,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF343434),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(32),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 27,
                top: 24,
                child: Text(
                  '9:42',
                  style: TextStyle(
                    color: const Color(0xFFF5F5F5),
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 90,
                child: Text(
                  'Business',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Roboto',
                    fontWeight: FontWeight.w700,
                    height: 0.80,
                    letterSpacing: 0.40,
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 118,
                child: Text(
                  'News',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Roboto',
                    fontWeight: FontWeight.w700,
                    height: 0.80,
                    letterSpacing: 0.40,
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 141,
                child: Container(width: 24, height: 24, child: Stack()),
              ),
              Positioned(
                left: 26,
                top: 205,
                child: SizedBox(
                  width: 289,
                  height: 108,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'NVIDIA (NVDA) Shares Surge 6% After AI Chip Announcement.\n\n',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        TextSpan(
                          text: 'The company unveiled its next-gen "Blackwell" AI processors, with pre-orders exceeding \$2B. Competitors AMD and Intel dipped 2%.\n',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 512,
                child: Text(
                  '5h ago',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 45,
                top: 338,
                child: Text(
                  '3h ago',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 42,
                top: 624,
                child: Text(
                  '6h ago',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 362,
                child: SizedBox(
                  width: 363,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: 'U.S. Stock Futures: All major indices are trending lower after last weeks declines, influenced by tariff uncertainties and global trade tensions.\n\n',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        TextSpan(
                          text: 'Dow Jones Industrial Average: Futures down 1.1%\nNasdaq: Futures down 1.6%\nS&P 500: Futures down 1.3%',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 145,
                child: SizedBox(
                  width: 338,
                  child: Text(
                    'Filter by keywords: "Stocks," "Crypto," "Fed Rates,"',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFF606060),
                      fontSize: 12,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w300,
                      height: 1.33,
                      letterSpacing: 0.40,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 534,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Commodities & Cryptocurrency.\n\n',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 14,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                      TextSpan(
                        text: 'Bitcoin (BTCUSD): Up 2%, trading around \$87,000.\nGold: Surged past \$3,400 an ounce.\nOil: Fell by 2%.',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 15,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                      TextSpan(
                        text: '​',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 14,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w300,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 31,
                top: 648,
                child: SizedBox(
                  width: 268,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: ' ',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 14,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                        TextSpan(
                          text: 'Tesla (NASDAQ: TSLA) & Alphabet (NASDAQ: GOOG)\n\n',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 14,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w700,
                          ),
                        ),
                        TextSpan(
                          text: 'Upcoming Earnings: Both companies are scheduled to report earnings this week, and investors are closely watching for performance insights amid the current economic volatility.',
                          style: TextStyle(
                            color: Colors.white,
                            fontSize: 15,
                            fontFamily: 'Inter',
                            fontWeight: FontWeight.w300,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 817,
                child: Text(
                  '9h ago',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 11,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 55,
                top: 7,
                child: Container(
                  width: 375,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(width: 375, height: 44),
                      ),
                      Positioned(
                        left: 336,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 338,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: Colors.white),
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 27,
                top: 56,
                child: Container(
                  width: 22,
                  height: 20,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 31,
                top: 926,
                child: Container(
                  width: 375,
                  height: 34,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 121,
                        top: 21,
                        child: Container(
                          width: 134,
                          height: 5,
                          decoration: ShapeDecoration(
                            color: const Color(0x7FB9C1D9),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(100),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 319,
                child: Text(
                  'see more',
                  style: TextStyle(
                    color: const Color(0xFF767676),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 233,
                top: 319,
                child: Text(
                  'see more',
                  style: TextStyle(
                    color: const Color(0xFF767676),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 260,
                top: 491,
                child: Text(
                  'see more',
                  style: TextStyle(
                    color: const Color(0xFF767676),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 311,
                top: 494,
                child: Container(width: 20, height: 17, child: Stack()),
              ),
              Positioned(
                left: 154,
                top: 609,
                child: Text(
                  'see more',
                  style: TextStyle(
                    color: const Color(0xFF767676),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 208,
                top: 612,
                child: Container(width: 20, height: 17, child: Stack()),
              ),
              Positioned(
                left: 289,
                top: 792,
                child: Container(width: 20, height: 17, child: Stack()),
              ),
              Positioned(
                left: 236,
                top: 789,
                child: Text(
                  'see more',
                  style: TextStyle(
                    color: const Color(0xFF767676),
                    fontSize: 12,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w400,
                  ),
                ),
              ),
              Positioned(
                left: 286,
                top: 322,
                child: Container(width: 20, height: 17, child: Stack()),
              ),
            ],
          ),
        ),
      ],
    );
  }
}