import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(body: ListView(children: [Premiumpage()])),
    );
  }
}

class Premiumpage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      extendBodyBehindAppBar: true,
      appBar: AppBar(
        backgroundColor: Colors.transparent,
        elevation: 0,
        leading: IconButton(
          icon: Icon(Icons.arrow_back, color: Colors.white),
          onPressed: () => Navigator.pop(context),
        ),
      ),
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
            colors: [Color(0xFF4C336F), Color(0xFF170201), Color(0xFF0D1531)],
            stops: [0.0, 0.2, 1.0],
          ),
        ),
        child: SingleChildScrollView(
          child: Padding(
            padding: EdgeInsets.only(top: kToolbarHeight + 20, bottom: 20),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 22),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Choose your pricing plan',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 21,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w900,
                        ),
                      ),
                    ],
                  ),
                ),
                SizedBox(height: 40),
                _buildPricingPlan('Basic', 19, Color(0xFF0A2F58), [
                  'Basic stock analysis',
                  'Limited watchlists',
                  'Standard market reports',
                  'Email support',
                ]),
                SizedBox(height: 20),
                _buildPricingPlan('Pro', 39, Color(0xFF0C1531), [
                  'Advanced stock analysis',
                  'Unlimited watchlists',
                  'Premium market reports',
                  'Priority support',
                ]),
                SizedBox(height: 20),
                _buildPricingPlan('Business', 79, Color(0xFF071850), [
                  'Professional trading tools',
                  'Team collaboration',
                  'Custom reports',
                  '24/7 dedicated support',
                ]),
                SizedBox(height: 20),
                _buildPricingPlan('Enterprise', 149, Color(0xFF0B2783), [
                  'Full API access',
                  'Custom solutions',
                  'Dedicated account manager',
                  'On-site training',
                ]),
              ],
            ),
          ),
        ),
      ),
    );
  }

  Widget _buildPricingPlan(
    String title,
    int price,
    Color backgroundColor,
    List<String> features,
  ) {
    return Container(
      margin: EdgeInsets.symmetric(horizontal: 20),
      padding: EdgeInsets.all(24),
      decoration: ShapeDecoration(
        color: backgroundColor,
        shape: RoundedRectangleBorder(
          side: BorderSide(width: 1, color: Color(0xFFEFF0F6)),
          borderRadius: BorderRadius.circular(24),
        ),
        shadows: [
          BoxShadow(
            color: Color(0x1414132A),
            blurRadius: 12,
            offset: Offset(0, 2),
            spreadRadius: 0,
          ),
        ],
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            title,
            style: TextStyle(
              color: Colors.white,
              fontSize: 24,
              fontFamily: 'DM Sans',
              fontWeight: FontWeight.w700,
            ),
          ),
          SizedBox(height: 16),
          Row(
            crossAxisAlignment: CrossAxisAlignment.end,
            children: [
              Text(
                '\$$price',
                style: TextStyle(
                  color: Color(0xFF34C759),
                  fontSize: 54,
                  fontFamily: 'DM Sans',
                  fontWeight: FontWeight.w700,
                  height: 1.22,
                ),
              ),
              Padding(
                padding: const EdgeInsets.only(bottom: 8.0),
                child: Text(
                  '/month',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'DM Sans',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
            ],
          ),
          SizedBox(height: 30),
          Text(
            'Premium Features',
            style: TextStyle(
              color: Color(0xFF34C759),
              fontSize: 18,
              fontFamily: 'DM Sans',
              fontWeight: FontWeight.w700,
              height: 1.11,
            ),
          ),
          SizedBox(height: 20),
          ...features.map((feature) => _buildFeatureItem(feature)).toList(),
          SizedBox(height: 20),
          Center(
            child: Container(
              width: 196,
              height: 44,
              decoration: ShapeDecoration(
                color: Color(0xFFBB6BD9),
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(24),
                ),
              ),
              child: Center(
                child: Text(
                  'Choose plan',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontFamily: 'Poppins',
                    fontWeight: FontWeight.w500,
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildFeatureItem(String text) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: Row(
        children: [
          Container(
            width: 26,
            height: 26,
            margin: EdgeInsets.only(right: 14),
            decoration: BoxDecoration(
              color: Color(0xFF34C759),
              shape: BoxShape.circle,
            ),
            child: Icon(Icons.check, color: Colors.white, size: 16),
          ),
          Expanded(
            child: Text(
              text,
              style: TextStyle(
                color: Color(0xFF34C759),
                fontSize: 16,
                fontFamily: 'DM Sans',
                fontWeight: FontWeight.w400,
                height: 1.25,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
