import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Homepage(),
        ]),
      ),
    );
  }
}

class Homepage extends StatelessWidget {
  const Homepage({super.key});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 440,
          height: 952,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF343434),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(32),
            ),
          ),
          child: Stack(
            children: [
              Positioned(
                left: 26,
                top: 17,
                child: Text(
                  '9:42',
                  style: TextStyle(
                    color: const Color(0xFFF5F5F5),
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 55,
                top: 121,
                child: Text(
                  'Search',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 15,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w300,
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 117,
                child: Container(width: 24, height: 24, child: Stack()),
              ),
              Positioned(
                left: 19,
                top: 50,
                child: Text(
                  'Stocks',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 23,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 28,
                top: 78,
                child: Text(
                  'April',
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 23,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
              Positioned(
                left: 25,
                top: 149,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Hey Omar Radwan\n',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w200,
                        ),
                      ),
                      TextSpan(
                        text: 'Welcome to TradeWise',
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Inter',
                          fontWeight: FontWeight.w700,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 34,
                top: 438,
                child: SizedBox(
                  width: 74.65,
                  child: Text(
                    'Portfolio',
                    style: TextStyle(
                      color: Colors.black,
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 340,
                top: 440,
                child: SizedBox(
                  width: 60.58,
                  child: Text(
                    'View all',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: const Color(0xFF007AFF) /* Colors-Blue */,
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.43,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 21,
                top: 479,
                child: Container(
                  width: 185,
                  height: 108,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 185,
                          height: 108,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF0A2F58),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 146,
                          height: 80,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 135,
                                  height: 44,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 40,
                                          height: 40,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://placehold.co/40x40"),
                                              fit: BoxFit.cover,
                                            ),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 56,
                                        top: 0,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 4,
                                          children: [
                                            Text(
                                              'APPL',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: const Color(0xFFEBFFEE) /* Text-Positive-On-Positive */,
                                                fontSize: 16,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w600,
                                                height: 1.50,
                                                letterSpacing: 0.10,
                                              ),
                                            ),
                                            Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              spacing: 4,
                                              children: [
                                                Text(
                                                  'Apple Inc.',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF757575),
                                                    fontSize: 12,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.33,
                                                    letterSpacing: 0.40,
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 56,
                                child: Text(
                                  '198.24',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFFEBFFEE) /* Text-Positive-On-Positive */,
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.50,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 106,
                                top: 59,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 1,
                                  children: [
                                    Container(
                                      width: 12,
                                      height: 12,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(),
                                    ),
                                    Text(
                                      '2.5%',
                                      style: TextStyle(
                                        color: const Color(0xFF039C6B),
                                        fontSize: 12,
                                        fontFamily: 'Roboto',
                                        fontWeight: FontWeight.w400,
                                        height: 1.33,
                                        letterSpacing: 0.40,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 230,
                top: 479,
                child: Container(
                  width: 185,
                  height: 108,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 185,
                          height: 108,
                          decoration: ShapeDecoration(
                            color: const Color(0xFFE3F4E1),
                            shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 146,
                          height: 80,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 135,
                                  height: 44,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 40,
                                          height: 40,
                                          decoration: ShapeDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage("https://placehold.co/40x40"),
                                              fit: BoxFit.cover,
                                            ),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(20),
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 56,
                                        top: 0,
                                        child: Column(
                                          mainAxisSize: MainAxisSize.min,
                                          mainAxisAlignment: MainAxisAlignment.start,
                                          crossAxisAlignment: CrossAxisAlignment.start,
                                          spacing: 4,
                                          children: [
                                            Text(
                                              'LYFT',
                                              textAlign: TextAlign.center,
                                              style: TextStyle(
                                                color: const Color(0xFF212121),
                                                fontSize: 16,
                                                fontFamily: 'Poppins',
                                                fontWeight: FontWeight.w600,
                                                height: 1.50,
                                                letterSpacing: 0.10,
                                              ),
                                            ),
                                            Row(
                                              mainAxisSize: MainAxisSize.min,
                                              mainAxisAlignment: MainAxisAlignment.start,
                                              crossAxisAlignment: CrossAxisAlignment.start,
                                              spacing: 4,
                                              children: [
                                                Text(
                                                  'Lyft Inc.',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: const Color(0xFF757575),
                                                    fontSize: 12,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w400,
                                                    height: 1.33,
                                                    letterSpacing: 0.40,
                                                  ),
                                                ),
                                              ],
                                            ),
                                          ],
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 1,
                                top: 56,
                                child: Text(
                                  '410.01',
                                  textAlign: TextAlign.center,
                                  style: TextStyle(
                                    color: const Color(0xFF212121),
                                    fontSize: 16,
                                    fontFamily: 'Poppins',
                                    fontWeight: FontWeight.w600,
                                    height: 1.50,
                                    letterSpacing: 0.10,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 106,
                                top: 59,
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.center,
                                  spacing: 1,
                                  children: [
                                    Container(
                                      width: 12,
                                      height: 12,
                                      clipBehavior: Clip.antiAlias,
                                      decoration: BoxDecoration(),
                                      child: Stack(),
                                    ),
                                    Text(
                                      '2.5%',
                                      style: TextStyle(
                                        color: const Color(0xFF039C6B),
                                        fontSize: 12,
                                        fontFamily: 'Roboto',
                                        fontWeight: FontWeight.w400,
                                        height: 1.33,
                                        letterSpacing: 0.40,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 204,
                child: Container(
                  width: 395,
                  height: 217,
                  decoration: ShapeDecoration(
                    color: const Color(0xFFE3EEFF),
                    shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                  ),
                ),
              ),
              Positioned(
                left: 287.95,
                top: 302.43,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                  width: 108.50,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      side: BorderSide(
                        width: 2,
                        strokeAlign: BorderSide.strokeAlignCenter,
                        color: const Color(0xFF1573FE),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 278.71,
                top: 320.33,
                child: Container(
                  width: 18.48,
                  height: 17.90,
                  decoration: ShapeDecoration(
                    color: const Color(0xFF1573FE),
                    shape: OvalBorder(
                      side: BorderSide(
                        width: 4,
                        color: const Color(0xFFC7DDFF),
                      ),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 38.57,
                top: 231.23,
                child: SizedBox(
                  width: 89.14,
                  height: 22.85,
                  child: Text(
                    'Stock Gains',
                    style: TextStyle(
                      color: const Color(0xFF616161),
                      fontSize: 14,
                      fontFamily: 'Roboto',
                      fontWeight: FontWeight.w400,
                      height: 1.43,
                      letterSpacing: 0.25,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 38.48,
                top: 255.45,
                child: SizedBox(
                  width: 144.37,
                  height: 31.32,
                  child: Text.rich(
                    TextSpan(
                      children: [
                        TextSpan(
                          text: '\$25,901.0.',
                          style: TextStyle(
                            color: Colors.black,
                            fontSize: 22,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.27,
                          ),
                        ),
                        TextSpan(
                          text: '41',
                          style: TextStyle(
                            color: const Color(0xFF616161),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.75,
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 253.30,
                top: 226.37,
                child: Opacity(
                  opacity: 0.60,
                  child: Container(
                    width: 143.22,
                    height: 40.27,
                    decoration: ShapeDecoration(
                      color: Colors.white,
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 281.02,
                top: 236.44,
                child: SizedBox(
                  width: 82,
                  height: 22.37,
                  child: Text(
                    'This week',
                    textAlign: TextAlign.right,
                    style: TextStyle(
                      color: const Color(0xFF212121),
                      fontSize: 14,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.43,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 361.87,
                top: 234.20,
                child: Container(
                  width: 27.72,
                  height: 26.85,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 20,
                top: 595,
                child: SizedBox(
                  width: 91.24,
                  child: Text(
                    'Watchlist',
                    style: TextStyle(
                      color: const Color(0xFFFEFEFE),
                      fontSize: 16,
                      fontFamily: 'Poppins',
                      fontWeight: FontWeight.w600,
                      height: 1.50,
                      letterSpacing: 0.10,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 387.28,
                top: 595,
                child: Container(
                  width: 27.72,
                  height: 24,
                  clipBehavior: Clip.antiAlias,
                  decoration: BoxDecoration(),
                  child: Stack(),
                ),
              ),
              Positioned(
                left: 20,
                top: 640,
                child: Container(
                  width: 395,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 55.44,
                          height: 48,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/55x48"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF606060),
                              ),
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 71.61,
                        top: 3,
                        child: Text(
                          'MSFT',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 344.25,
                        top: 3,
                        child: Text(
                          '\$213.10',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 351.32,
                        top: 26,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 1,
                          children: [
                            Container(
                              width: 12,
                              height: 12,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              '2.5%',
                              style: TextStyle(
                                color: const Color(0xFF6BBDFF),
                                fontSize: 12,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w400,
                                height: 1.33,
                                letterSpacing: 0.40,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Positioned(
                        left: 71.61,
                        top: 26,
                        child: Text(
                          'Microsoft Corp.',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 712,
                child: Container(
                  width: 395,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 55.44,
                          height: 48,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/55x48"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFF606060),
                              ),
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 71.61,
                        top: 3,
                        child: Text(
                          'GOOGL',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 344.25,
                        top: 3,
                        child: Text(
                          '\$213.10',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 351.32,
                        top: 26,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 1,
                          children: [
                            Container(
                              width: 12,
                              height: 12,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              '1.1%',
                              style: TextStyle(
                                color: const Color(0xFF07F7B4),
                                fontSize: 12,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w400,
                                height: 1.33,
                                letterSpacing: 0.40,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Positioned(
                        left: 71.61,
                        top: 26,
                        child: Text(
                          'Alphabet Inc.',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 20,
                top: 784,
                child: Container(
                  width: 395,
                  height: 48,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 55.44,
                          height: 48,
                          decoration: ShapeDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://placehold.co/55x48"),
                              fit: BoxFit.cover,
                            ),
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                color: const Color(0xFFEEEEEE),
                              ),
                              borderRadius: BorderRadius.circular(24),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 71.61,
                        top: 3,
                        child: Text(
                          'SPOT',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 16,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.50,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 344.25,
                        top: 3,
                        child: Text(
                          '\$213.10',
                          textAlign: TextAlign.right,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 14,
                            fontFamily: 'Poppins',
                            fontWeight: FontWeight.w600,
                            height: 1.43,
                            letterSpacing: 0.10,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 351.32,
                        top: 26,
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          spacing: 1,
                          children: [
                            Container(
                              width: 12,
                              height: 12,
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Stack(),
                            ),
                            Text(
                              '2.5%',
                              style: TextStyle(
                                color: const Color(0xFFFFB129),
                                fontSize: 12,
                                fontFamily: 'Roboto',
                                fontWeight: FontWeight.w400,
                                height: 1.33,
                                letterSpacing: 0.40,
                              ),
                            ),
                          ],
                        ),
                      ),
                      Positioned(
                        left: 71.61,
                        top: 26,
                        child: Text(
                          'Microsoft Corp.',
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 1,
                top: 865,
                child: Container(
                  width: 439,
                  height: 95,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 9.05,
                        child: Container(
                          width: 439,
                          height: 85.95,
                          decoration: BoxDecoration(
                            color: const Color(0xFF434343),
                            boxShadow: [
                              BoxShadow(
                                color: Color(0x19000000),
                                blurRadius: 1,
                                offset: Offset(0, -1),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 189.11,
                        top: 2.26,
                        child: Container(
                          width: 63.04,
                          height: 63.33,
                          decoration: ShapeDecoration(
                            color: const Color(0xFF606060),
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(50),
                            ),
                            shadows: [
                              BoxShadow(
                                color: Color(0x3F000000),
                                blurRadius: 8,
                                offset: Offset(0, 2),
                                spreadRadius: 0,
                              )
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 207.12,
                        top: 20.36,
                        child: Container(
                          width: 27.02,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 293.79,
                        top: 21.49,
                        child: Container(
                          width: 27.02,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 37.15,
                        top: 21.49,
                        child: Container(
                          width: 27.02,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 33.52,
                        top: 52.02,
                        child: Text(
                          'Home',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFF89B8FF),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 110.44,
                        top: 52.02,
                        child: Text(
                          'Business\n news',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 287.79,
                        top: 52.02,
                        child: Text(
                          'View\nMarket',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 373.46,
                        top: 52.02,
                        child: Text(
                          'Profile',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: const Color(0xFFFEFEFE),
                            fontSize: 12,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 1.33,
                            letterSpacing: 0.40,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 122.69,
                        top: 21.49,
                        child: Container(
                          width: 27.02,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                      Positioned(
                        left: 379.34,
                        top: 21.49,
                        child: Container(
                          width: 27.02,
                          height: 27.14,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 46,
                top: 2,
                child: Container(
                  width: 375,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(width: 375, height: 44),
                      ),
                      Positioned(
                        left: 336,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              color: Colors.white,
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 338,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(color: Colors.white),
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}